<template>
  <!-- eslint-disable -->
  <div class="pg-static">
    <div class="pg-static-banner licensing">
      <div class="pg-static-banner-overlay">
        <div class="banner-heading">
          <h1>Licensing</h1>
        </div>
      </div>
    </div>
    <div class="section section-wrapper">
      <h1 class="feature-text text-large">LICENSING AGREEMENT FOR ORDERING AND RECEIVING HONELY DATA</h1>
      <div class="static-body feature-text text-exsmall list-normal static-subheadings list-ordered">
        <p>Honely, LLC (&ldquo;Honely&rdquo;) provides a menu of several proprietary AI data-driven solutions (&ldquo;Technology Solutions&rdquo;) for predicting a residential property&rsquo;s value either currently or into the future.  The data from several of these Solutions are available free-of-charge to Our Registered Users on Our Website under the terms of this Licensing Agreement.</p>
        <p>Registered Users may avail themselves of one or more of these Solutions free-of-charge by agreeing to comply with the terms of this Licensing Agreement (&ldquo;Agreement&rdquo;) as an approved Licensee of one or more of Honely&rsquo;s offered Solutions.   If you are applying as a Licensee in your individual capacity, you agree to be bound by the following terms and conditions.  If you are applying on behalf of the named organization, you are representing that you have the authorization to bind the organization to the following terms and conditions.</p>
        <p>For information on Honely&rsquo;s customized Technology Solutions, including Honely&rsquo;s data analyses, please contact us at info@honely.com.</p>
        <ol>
          <li>
            DEFINITIONS
            <p>Intepretation:</p>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            <p>&ldquo;Affiliate(s)&rdquo; means any third parties with whom You may have a business relationship involving the sale of, purchase of, or investment in real estate.</p>
            <p>&ldquo;Company&rdquo; (referred to as either &ldquo;the Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo; or &ldquo;Our&rdquo; in this Agreement) means Honely, LLC, a Florida Corporation with a business address of 150 E Palmetto Park Road, Suite 800, Boca Raton, Florida 33432.  Under the terms of this Agreement, Honely, LLC is the Licensor of this Agreement’s licensed subject matter.</p>
            <p>&ldquo;End User&rdquo; means the Person who is subscribing to one or more of Honely&rsquo;s Technology Solutions driven Solutions as the Licensee and who will be the recipient of the Honely Data.  Where the Person is a legal entity or organization, End User means the designated individuals (s) who may be given access to the Honely Data on a need-to-know basis.</p>
            <p>&ldquo;Honely Data&rdquo; means Honely&rsquo;s proprietary data and information, including but not limited to raw data, data analysis, and reports generated by our proprietary AI data- driven solutions technology for You as a Licensee.  As a Licensee under this Agreement, you are being provided with certain Honely Data being made available to you free-of-charge which you select to receive.</p>
            <p>&ldquo;Honely Intellectual Property&rdquo; means Honely&rsquo;s copyrights, trade secrets, good will, patents, and registered and common law trademarks and any other intellectual property on a worldwide basis in and to any and all of Honely&rsquo;s analytical and statistical data, reports, projections, website content and design, software code and programs, and the Honely Data. The license grant under this Agreement pertains only to Honely Data to be provided to You and Your right to access Our Website to make calls to Our server as specified in Section 4(d) below to obtain Honely Data and use it for the limited purposes herein.</p>
            <p>&ldquo;Honely&rsquo;s Technology Solution(s)&rdquo; means Honely&rsquo;s proprietary AI-driven Technology Solutions(s) which generate the Honely Data.</p>
            <p>&ldquo;Licensed Content&rdquo; means the Honely Data being made available to You free-of-charge. The Licensed Content to be provided by Honely is limited to data emanating from Honely&rsquo;s Solutions Technologies which Honely, in its sole discretion, is electing to provide to You free-of-charge.</p>
            <p>&ldquo;Person&rdquo; means an individual, a corporation, partnership, limited liability company, association, trust, unincorporated organization, or other legal entity or organization, or a Government Body who is entering into this Agreement as a Licensee.</p>
            <p>&ldquo;You&rdquo; or &ldquo;Your&rdquo; means the Licensee.</p>
            <p>&ldquo;Website&rdquo; or &ldquo;Site&rdquo; mean
              <a
                class="static-hyperlink"
                href="https://www.honely.com"
              >
                www.honely.com
              </a> through which You will receive certain Honely Data subject to the terms of this Licensing Agreement.
            </p>
          </li>
          <li>
            HONELY&rsquo;S WEBSITE-BASED SOLUTIONS
            <p>Honely is providing certain Honely data generated by its Honely Technology Solutions free-of-charge.   If Honely approves you as a Licensee for its free-of-charge Website-Based programs and, subject to the terms of this Agreement, you will be able to make calls to Our server through Our Website to receive current Honely Data for your selected free-of-charge Website offerings for which you have been approved as a Licensee.</p>
          </li>
          <li>
            REVOCABLE, NON-EXCLUSIVE LICENSE TO UTILIZE THE HONELY DATA GENERATED BY OUR PROPRIETARY AI SOLUTIONS
            <p>If you are approved by Honely as a Licensee of our free-of-charge Web-Based Solution(s), and subject to the terms of this Agreement, you will receive the Honely Data generated by Our Technology Solutions.  You agree that You, as an End User, will receive the Honely Data generated by Our Technology Solutions on an &ldquo;as is&rdquo; basis with disclaimers substantially equivalent to those set forth in Sections 11 and 12.   You also agree to comply with the following provisions of this Section 3.</p>
            <ol type="a">
              <li>You agree to keep the Honely Data confidential, and not to share it with any third party. This license is personal to You, and any of Your Affiliates must seek and obtain their own license with Us.  We reserve the right to decline entering into a license with any Affiliate who applies for a license.</li>
              <li>You may present the Honely Data only on a transactional basis.</li>
              <li>If You are a legal entity or organization, You are required to limit the number of End Users and keep a record of all End Users who may have access to the Honely Data on a need-to-know basis.</li>
              <li>You are forbidden to republish the Honely Data.  You are forbidden to make the Honely Data publicly available.  You should not retain any copies of the Honely Data.   The Honely Data are time-sensitive and may change from month-to-month depending on the dynamics of the real estate market. You should obtain updated Honely Data which will be available to You under the terms of this Agreement.</li>
              <li>Your license to the Honely Data is limited to: (i) making direct server calls to the Honely AI-Solution(s) You have subscribed to; (b) receiving the Honely Data generated by that AI-Solution; (c) using it in accordance with this Agreement.</li>
              <li>You may not present the Honely Data (or permit the Honely Data to be presented) so that it appears to be available from a third-party website and not
                <a
                  class="static-hyperlink"
                  href="https://www.honely.com"
                >
                  www.honely.com
                </a>.
              </li>
              <li>You may not use the Honely Data for direct marketing (i.e., mailing) or telemarketing lists.</li>
              <li>You may not separate address information for a specific property included in the Honely Data You receive for a Residential Property Value Estimate.   You may not separate any for-sale information or any for-rent information presented with any Honely Data.   You may not separately extract and provide or otherwise use data elements from the Honely Data to enhance the data files of third parties.</li>
              <li>You further agree not to otherwise reproduce, modify, distribute, decompile, disassemble or reverse engineer any portion of the Honely AI or any of the Honely Data provided to You.</li>
              <li>If You become aware that any End User of the Honely Data is in material breach of any provision of this Section 3 or any other provision in this Agreement, You are required to comply with under this Agreement, or our Website&rsquo;s Terms of Use which You agreed to comply with as a Registered User of Our Website pursuant to this Section 3, and the Honely Branding and Display Requirements (the &ldquo;Applicable Terms&rdquo;), then you agree to promptly notify Honely of such breach by e-mail to info@Honely.com and to take prompt commercially reasonable corrective action at Your expense to remedy such breach. In addition, upon Honely&rsquo;s request, you will either (i) use commercially reasonable efforts to obtain such equitable relief to prevent harm to Honely or its other licensors, or (ii) assign any of your applicable rights to permit Honely to seek such equitable relief.</li>
              <li>Further, pursuant to Section 8 below, Honely may terminate Your use of the Honely Solutions Technology, the Honely Data and the Honely Brand &amp; Links if and when Honely determines that Your use is inappropriate.  Additionally, Honely may seek injunctive relief and pursue other legal remedies for violation of this Section 3.</li>
            </ol>
          </li>
          <li>
            ACCEPTABLE USE
            <ol type="a">
              <li>You agree not to use the Website, the Honely Data, or Honely Brand &amp; Links in any way that is unlawful, or harms Honely, its service providers, its suppliers, or any other person.</li>
              <li>You agree not to remove any Honely copyright notices, watermarks, or any other provided markings identifying Honely as the owner of the Licensed Content.</li>
              <li>You may not use the Honely Data to provide a service for other businesses.</li>
              <li>You <span class="static-underline">will not</span> make any attempt to access Honely&rsquo;s proprietary AI-Driven Solutions technology at any time.  Your license is strictly limited to using Our website to call Our server(s) requesting Honely Data pursuant to this Agreement which pertains only to limited free-of-charge Honely Data We are making available to You under the terms of this Agreement.</li>
              <li>You must use commercially reasonable efforts to prevent the Honely Data from being downloaded in bulk or otherwise scraped. Such efforts include but are not limited to &ldquo;spider traps,&rdquo; &ldquo;C.A.P.T.C.H.A.,&rdquo; velocity checks, or source IP analysis.</li>
              <li>Further, pursuant to Section 8 below, Honely may terminate Your use of the Honely Data and Honely Brand &amp; Links if and when Honely determines that Your use is inappropriate.</li>
              <li>Further, pursuant to Section 8 below, Honely may terminate Your use of the Honely Solutions Technology, the Honely Data and the Honely Brand &amp; Links if and when Honely determines that Your use is inappropriate.  Additionally, Honely may seek injunctive relief and pursue other legal remedies for violation of this Section 4.</li>
            </ol>
          </li>
          <li>
            LIMITED RELATIONSHIP
            <p>You and Honely are independent contractors, and nothing in this Agreement shall be construed as creating an employer-employee relationship, a partnership, or a joint venture. While You may publicly refer to the fact that you have utilized our Website, You agree not to make any other public statements that assert or imply any other relationship with Honely, unless you have Honely's prior written approval.</p>
          </li>
          <li>
            HONELY&rsquo;S INTELLECTUAL PROPERTY
            <p>The Honely AI-Driven Solutions Technology, Honely Data, and Honely Brand &amp; Links are the property of Honely, and comprise Honely&rsquo;s valuable Intellectual Property.   Any unauthorized usage of Honely&rsquo;s Intellectual Property may subject You to legal action.  As stated in Section 4, You shall not remove any references to Honely included with the Honely Data You receive from Honely by email.  Any such removal may constitute a violation of 15 U.S.C. 1202(a) and subject You to litigation.</p>
            <p>You acknowledge and agree that in the event of a breach or threatened violation of Our intellectual property rights and Confidential and Proprietary Information by You, we will suffer irreparable harm and will therefore be entitled to injunctive relief to enforce this Agreement pursuant to Section 13. Accordingly, we may, without waiving any other remedies under this Agreement, seek from any court having jurisdiction any interim, equitable, provisional, or injunctive relief that is necessary to protect Our rights and intellectual property pending the outcome of any arbitration proceeding, if any, referenced below. You hereby irrevocably and unconditionally consent to the personal and subject matter jurisdiction of the federal and state courts in the State of Florida for purposes of any such action by us.</p>
          </li>
          <li>
            CHANGES
            <p>Honely reserves the right to change this Agreement&rsquo;s terms in addition to <span class="static-underline">Our Terms of Use</span> governing this Website and <span class="static-underline">Our Privacy Policy</span> at any time.  You are responsible for reviewing Our Website for any updated Agreement, Terms of Use, and Privacy Policy. Your continued access to our free-of-charge Honely Data after the designated effective date of such changes will constitute acceptance of and agreement to any such changes.</p>
          </li>
          <li>
            TERMINATION
            <p>Honely may change, suspend or discontinue Your receipt of the Honely Data being provided under this Agreement at any time for any reason without notice.  If We terminate this Agreement for Your material breach of this Agreement, <span class="static-underline">You may be subject to legal action.</span></p>
            <p>You may also terminate this Agreement by notifying Us at info@honely.com</p>
          </li>
          <!-- <li>
            LICENSING FEE
            <p>By entering into this Licensing Agreement, You are Agreeing that Your Credit Card on file with Honely&rsquo;s Third-Party Payee will be charged once a month at the monthly subscription rate calculated by Our website until the Agreement is terminated. As stated in Our Privacy Policy, please review our Third-Party Payee&rsquo;s own Privacy Policy governing its usage of personal identifying information including Your credit card number.</p>
            <p>You are limited to the number of monthly AI calls your Subscription(s) designate(s). You may increase the number of available AI calls for a Subscribed-to Solution by paying an additional monthly subscription fee. See <a href="https://www.honely.com">www.honely.com</a> for more information.</p>
          </li>
          <li>
            FORCE MAJEURE
            <p>To the extent caused by <i>force majeure</i>, no delay, failure, or default will constitute a breach of this Agreement where the cause or occurrence is beyond the reasonable control of the affected Party and whether or not foreseeable by such Party. If any delay or non-performance due to force majeure exceeds thirty (30) calendar days or appears that it will exceed 30 calendar days, the Party not affected by force majeure reserves the right to terminate this Agreement by written notice. Alternatively, the Parties may renegotiate the term of the Agreement to accommodate any delay in the providing of the Services as the result of a <i>force majeure</i> event including but not limited to fire, tropical storms, hurricanes, earthquakes, pandemics, or loss of power, as an Amendment to this Agreement should both Parties be in favor of doing so.</p>
            <p>The foregoing notwithstanding and with the exception of payment obligations, if, as the direct or indirect result of any Force Majeure Event, the Parties&rsquo; continued performance hereunder becomes irreparably impaired or prevented, the Parties may mutually agree to terminate this Agreement, in whole or in part, with no further obligation or liability; provided, however, that certain provisions of this Agreement shall survive any such termination pursuant to Section 16 (c).</p>
          </li> -->
          <li>
            CONTROLLING LAW, JURISDICTION, &amp; VENUE
            <p>These Terms will be governed by the laws of the state of Florida.  Notwithstanding Article 15, the exclusive court jurisdiction for any claim, action or dispute between the Parties or relating in any way to this Agreement for any injunctive remedy Honely may seek under Sections 3, 4 and/or 6 shall be the state or federal courts of the State of Florida.  The venue for the adjudication or disposition of any such claim, action or dispute under Section 13 shall be in Florida.</p>
            <p>The terms of this Agreement are governed by the laws of the State of Florida, without giving effect to its conflict of laws provisions for any and all disputes, claims and actions arising from or in connection with the Services and/or this Licensing Agreement.  Each party shall be responsible for their own attorneys&rsquo; fees and costs.</p>
          </li>
          <li>
            INDEMNITY
            <p>You agree to hold harmless and indemnify Honely, and its subsidiaries, affiliates, officers, agents, employees, and suppliers, from and against any third-party claim arising from or in any way related to Your use of the Honely Data, or Honely Brand &amp; Links other than as set forth in the Honely AI Network Branding and Display Requirements, violation of this Licensing Agreement or other actions connected with use of Honely services, including any liability or expense arising from all claims, losses, damages (actual and consequential), suits, judgments, litigation costs and attorneys&rsquo; fees, of every kind and nature. In such a case, Honely will (a) promptly provide You with written notice of such claim, suit or action; (b) provide You with reasonable information, assistance and cooperation, at Your expense, in defending the lawsuit or proceeding; and (c) give You full control and sole authority over the defense and settlement of such claim, subject to Honely&rsquo;s approval of any such settlement, which approval will not be unreasonably withheld or delayed.</p>
          </li>
          <li>
            NO WARRANTY
            <p>HONELY PROVIDES THE HONELY AI, HONELY DATA, HONELY WEBSITE AND HONELY BRAND &amp; LINKS &ldquo;AS IS,&rdquo; &ldquo;WITH ALL FAULTS&rdquo; AND &ldquo;AS AVAILABLE,&rdquo; AND THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY, AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HONELY AND ITS SUPPLIERS MAKE NO REPRESENTATIONS, WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED. HONELY AND ITS SUPPLIERS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES OR CONDITIONS, EXPRESS, STATUTORY AND IMPLIED, INCLUDING WITHOUT LIMITATION (A) WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, WORKMANLIKE EFFORT, ACCURACY, TITLE, QUIET ENJOYMENT, NO ENCUMBRANCES, NO LIENS AND NON-INFRINGEMENT, (B) WARRANTIES OR CONDITIONS ARISING THROUGH COURSE OF DEALING OR USAGE OF TRADE, AND (C) WARRANTIES OR CONDITIONS OF UNINTERRUPTED OR ERROR-FREE ACCESS OR USE.</p>
          </li>
          <li>
            LIABILITY LIMITATION; EXCLUSIVE REMEDY.
            <p>IN NO EVENT WILL HONELY OR ANY SUPPLIER BE LIABLE FOR ANY DAMAGES, INCLUDING WITHOUT LIMITATION ANY INDIRECT, CONSEQUENTIAL, SPECIAL, INCIDENTAL, OR PUNITIVE DAMAGES ARISING OUT OF, BASED ON, OR RESULTING FROM THESE AI TERMS OF USE OR YOUR USE OF HONELY’S AI, HONELY DATA, OR HONELY BRAND &amp; LINKS, EVEN IF SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE EXCLUSION OF DAMAGES UNDER THIS PARAGRAPH IS INDEPENDENT OF YOUR EXCLUSIVE REMEDY AND SURVIVES IN THE EVENT SUCH REMEDY FAILS OF ITS ESSENTIAL PURPOSE OR IS OTHERWISE DEEMED UNENFORCEABLE. THESE LIMITATIONS AND EXCLUSIONS APPLY WITHOUT REGARD TO WHETHER THE DAMAGES ARISE FROM (A) BREACH OF CONTRACT, (B) BREACH OF WARRANTY, (C) NEGLIGENCE, OR (D) ANY OTHER CAUSE OF ACTION, TO THE EXTENT SUCH EXCLUSION AND LIMITATIONS ARE NOT PROHIBITED BY APPLICABLE LAW. IF YOU DO NOT AGREE WITH ANY PART OF THESE LICENSING TERMS OF USE, OR YOU HAVE ANY DISPUTE OR CLAIM AGAINST HONELY OR ITS SUPPLIERS WITH RESPECT TO THESE TERMS OF USE OR THE SERVICES, THEN YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE HONELY WEBSITE TO MAKE SERVER CALLS, THE HONELY DATA, AND THE HONELY BRAND &amp; LINKS.</p>
            <p>Any damages awarded to the Licensee in a legal dispute arising under this Agreement shall not exceed $1.00.</p>
          </li>
          <li>
            ALTERNATIVE DISPUTE RESOLUTION
            <p>Notwithstanding Honely&rsquo;s right to seek an injunction under Sections 3, 4 and/or 6, in the event of a dispute arising under or relating to this Agreement or the Site (each, a &ldquo;<span class="static-underline">Dispute</span>&rdquo;), the parties agree to first make a good-faith effort to resolve any disagreement arising out of, or in connection with, this Agreement through negotiation. Should the Parties fail to resolve any such disagreement within ten (10) business days, the Parties may agree to continue their negotiations.</p>
            <p>Unless the parties can settle their differences through negotiation or further attempts at negotiation appear futile, any dispute, controversy or claim arising out of or relating to this Agreement, or the breach, termination or invalidity thereof, or any other dispute, controversy or claim between either of the parties hereto shall be settled by binding arbitration in accordance with the Federal Arbitration Act (&ldquo;<span class="static-underline">FAA</span>&rdquo;). NEITHER PARTY SHALL HAVE THE RIGHT TO LITIGATE SUCH CLAIM IN COURT OR TO HAVE A JURY TRIAL.  All disputes will be resolved before one (1) neutral arbitrator selected jointly by the parties, whose decision will be final, except for a limited right of appeal under the FAA. The arbitration shall be commenced and conducted by JAMS pursuant to its then current Comprehensive Arbitration Rules and Procedures and in accordance with the Expedited Procedures in those rules, or, where appropriate, pursuant to JAMS&rsquo; Streamlined Arbitration Rules and Procedures. All applicable JAMS&rsquo; rules and procedures are available at the JAMS Site <span class="static-underline">www.jamsadr.com</span>. Each party will be responsible for paying any JAMS filing, administrative, and arbitrator fees in accordance with JAMS rules. Judgment on the arbitrator&rsquo;s award may be entered in any court having jurisdiction. The arbitration may be conducted in person, through the submission of documents, by phone, or online. If conducted in person, the arbitration proceeding shall take place in Boca Raton, Florida. The parties shall cooperate in good faith in the voluntary and informal exchange of all non-privileged documents and other information (including electronically stored information) relevant to the dispute immediately after commencement of the arbitration.</p>
            <p>We may also seek the appointment of an Emergency Arbitrator through JAMS to address and decide a request for injunctive relief in emergent circumstances, including but not limited to the unauthorized dissemination of or infringement of or unauthorized use of Our intellectual property.  Nothing in the preceding sentence and nothing in this Section shall bar Us from instead seeking injunctive relief in emergent circumstances including but not limited to the unauthorized dissemination of or infringement of intellectual property from a Florida court of law pending the outcome of the arbitration proceeding.</p>
          </li>
          <li>
            MISCELLANEOUS
            <ol type = "a">
              <li>
                <a
                class="static-hyperlink"
                href="https://www.lawinsider.com/clause/legal-authority"
                >
                  Legal Authority.
                </a> If You are entering into this Agreement on behalf of a corporation or other entity duly organized and validly existing entity under the laws of the jurisdiction of its incorporation or formation, You are representing and warranting  that You have the legal power, authority and right to enter into, and perform its obligations under this Agreement.</li>
              <li><span class="static-underline">Assignment; Binding Effect.</span> Except as expressly provided hereunder, neither this Agreement, nor any rights or obligations hereunder, may be assigned or delegated by the Licensee without Honely&rsquo;s prior written consent.   Honely may assign this Agreement to a successor in interest at any time without the Licensee&rsquo;s consent.  However, any Assignee or successor in interest of Honely, LLC shall have no obligation whatsoever to continue providing the Honely Data under the terms of this Agreement.  Honely&rsquo;s rights under this Agreement shall inure to the benefit of its successors and assignees.  Any assignment by the Licensee not in accordance with this Section 14(b) shall be null and void.  Any assignment made by Honely of this Agreement shall not require the Licensee&rsquo;s consent and shall be considered valid if made in writing and signed by Honely and the assignee.</li>
              <li><span class="static-underline">Survival of Provisions.</span> When this Agreement is terminated in accordance with the termination provision in Section 8, such termination shall not affect the validity of the following provisions of these Terms, which shall remain in full force and effect indefinitely: &ldquo;Revocable, Non-Exclusive License to Utilize Honely’s Data&rdquo;; &ldquo;Acceptable Use&rdquo;; &ldquo;Limited Relationship&rdquo;; &ldquo;Honely&rsquo;s Intellectual Property&rdquo;; &ldquo;Controlling Law, Jurisdiction, and Venue&rdquo;; &ldquo;Indemnity;&rdquo; &ldquo;No Warranty&rdquo;; &ldquo;Liability Limitation and Exclusive Remedy&rdquo;; &ldquo;Binding Arbitration&rdquo;; and &ldquo;Miscellaneous.&rdquo;</li>
              <li><span class="static-underline">No Waiver.</span> Our failure to act on or enforce any provision of this Agreement shall not be construed as a waiver of that provision or any other provision of this Agreement. No waiver shall be effective against us unless made in writing, and no such waiver shall be construed as a waiver in any other or subsequent instance. Except as expressly agreed by us and You in writing this Agreement constitutes the entire agreement between You and Us with respect to the subject matter, and supersedes all previous or contemporaneous agreements, whether written or oral, between the Parties with respect to the subject matter.</li>
              <li><span class="static-underline">Severability.</span> Any term or provision of this Agreement which is invalid or unenforceable in any jurisdiction shall, as to that jurisdiction, be ineffective to the extent of such invalidity or unenforceability without rendering invalid or unenforceable the remaining terms and provisions of this Agreement or affecting the validity or enforceability of any of the terms or provisions of this Agreement in any other jurisdiction. If any provision of this Agreement is so broad as to be unenforceable, the provision shall be interpreted to be only so broad as is enforceable.</li>
              <li><span class="static-underline">Entire Agreement.</span> This Licensing Agreement between Honely and You constitutes the entire Agreement between the Parties.  Any modifications of or amendments to this Agreement must be made in writing and signed by the Parties. An effective date must be specified for any and all modifications and amendments.</li>
              <li><span class="static-underline">Headings.</span>  Headings of the Sections of this Agreement are for the convenience of the Parties only, and shall be given no substantive or interpretive effect whatsoever.</li>
            </ol>
          </li>
        </ol>
      </div>
    </div>
  </div>
  <!-- eslint-enable -->
</template>
